services:
  docs:
    image: zsmotor_local_docs
    container_name: zsmotor_local_docs
    build:
      context: zsmotor
      dockerfile: compose/local/docs/Dockerfile
    env_file:
      - compose/.envs/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./zsmotor:/app/zsmotor:z
    ports:
      - '9000:9000'
    command: /start-docs
